# Project information
site_name: BIH HPC Docs
site_description: Public documentation of the BIH HPC infrastructure.
site_author: BIH HPC IT
site_url: https://bihealth.github.io/bih-cluster

# Repository
repo_name: BIH HPC Docs
repo_url: https://github.com/holtgrewe/bih-cluster-test/
edit_uri: 'edit/master/bih-cluster/docs/'

# Copyright
copyright: 2016-2020, BIH HPC IT

# Theming, Configuration
theme: material
# strict: true

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - index.md
  - "Administrative":
    - "Getting Access": admin/getting-access.md
    - "Resource Registration": admin/resource-registration.md
    - "Maintenance etc.": admin/maintenance.md
  - "Getting Help":
    - "HPC Helpdesk": help/helpdesk.md
    - "Good Tickets": help/good-tickets.md
    - "Frequently Asked Questions": help/faq.md
  - "Manual":
    - "For the Impatient": manual/for-the-impatient.md
    - "Architecture": manual/architecture.md
    - "Job Scheduler": manual/job-scheduler.md
    - "Storage Volumes": manual/storage.md
  - "Connecting":
    - "Generate Keys": connecting/generate-key.md
    - "Submit Keys": connecting/submit-key.md
    - "Configure Client": connecting/configure-ssh.md
    - "From External": connecting/from-external.md
  - "Slurm Scheduler":
    - slurm/quickstart.md
    - slurm/cheat-sheet.md
    - slurm/migrating.md
    - slurm/job-scripts.md
    - slurm/snakemake.md
    - slurm/rosetta-stone.md
    - "X11 Forwarding": slurm/x11.md
  - "Best Practice":
    - "Project Structure": best-practice/project-structure.md
    - "Software Craftmanship": best-practice/software-craftmanship.md
    - "Using Screen/Tmux": best-practice/screen-tmux.md
    - "~/.bashrc Guide": best-practice/bashrc-guide.md
    - "Temporary Files": best-practice/temp-files.md
    - "Custom Environment Modules": best-practice/env-modules.md
  - "Cubit Static Data":
    - "Overview": cubit/index.md
    - "Annotations": cubit/annotations.md
    - "Application Support": cubit/app-support.md
    - "Databases": cubit/databases.md
    - "Exomes and Panels": cubit/exomes-panels.md
    - "Exon Lists": cubit/exon-lists.md
    - "Precomputed Indexes": cubit/index-files.md
    - "Reference Sequences": cubit/references.md
  - "How-To":
    - "Contribute to Docs": how-to/misc/contribute.md
    - "High-Memory Nodes": how-to/connect/high-memory.md
    - "GPU Nodes": how-to/connect/gpu-nodes.md
    - "OpenMPI": how-to/software/openmpi.md
    - "Scientific Software": how-to/software/scientific-software.md
    - "Cell Ranger": how-to/software/cell-ranger.md
    - "Jupyter": how-to/software/jupyter.md
    - "Keras": how-to/software/keras.md
    - "Matlab": how-to/software/matlab.md
    - "Tensorflow": how-to/software/tensorflow.md
    - "File Exchange": how-to/service/file-exchange.md
  - "Miscellaneous":
    - "Publication List": misc/publication-list.md
    - "External Guides": misc/external-resources.md
    - "Misc. Tips": misc/tips.md
    - "SSH Basics": misc/ssh-basics.md
